language: go

go:
  - 1.9

branches:
  only:
    - master

cache:
  directories:
    - $GOPATH/pkg/dep

before_install:
  # Setup some env variables
  - GO_FILES=$(find . -iname '*.go' | grep -v /vendor/)  # All the .go files, excluding vendor/
  - PKGS=$(go list ./... | grep -v /vendor/)             # All the import paths, excluding vendor/

  - go get -u github.com/golang/dep/cmd/dep
  - go get github.com/mitchellh/gox
  - go get github.com/tcnksm/ghr


install:
  - dep ensure


after_success:
  - gox -output "dist/{{.OS}}_{{.Arch}}_{{.Dir}}"
  - ghr --username reflog --token $GITHUB_TOKEN --replace --prerelease --debug pre-release dist/